;**********************************************************************************************;
; @description : Port Multiplexer Peripheral Register Definition                               ;
;**********************************************************************************************;

;**********************************************************************************************;
; @section : CTRLA - Control A                                                                 ;
;**********************************************************************************************;

; CTRLA - CCL LUT 1 Output
.EQU PORTMUX_CTRLA_LUT1_DEF = 0
.EQU PORTMUX_CTRLA_LUT1_ALT = 1

; CTRLA - CCL LUT 0 Output
.EQU PORTMUX_CTRLA_LUT0_DEF = 0
.EQU PORTMUX_CTRLA_LUT0_ALT = 1

; CTRLA - Event Output 2
.EQU PORTMUX_CTRLA_EVOUT2_OFF = 0
.EQU PORTMUX_CTRLA_EVOUT2_ON  = 1

; CTRLA - Event Output 1
.EQU PORTMUX_CTRLA_EVOUT1_OFF = 0
.EQU PORTMUX_CTRLA_EVOUT1_ON  = 1

; CTRLA - Event Output 0
.EQU PORTMUX_CTRLA_EVOUT0_OFF = 0
.EQU PORTMUX_CTRLA_EVOUT0_ON  = 1

;**********************************************************************************************;
; @section : CTRLB - Control B                                                                 ;
;**********************************************************************************************;

; CTRLB - TWI0 Communication
.EQU PORTMUX_CTRLB_TWI0_DEF = 0
.EQU PORTMUX_CTRLB_TWI0_ALT = 1

; CTRLB - SPI0 Communication
.EQU PORTMUX_CTRLB_SPI0_DEF = 0
.EQU PORTMUX_CTRLB_SPI0_ALT = 1

; CTRLB - USART0 Communication
.EQU PORTMUX_CTRLB_USART0_DEF = 0
.EQU PORTMUX_CTRLB_USART0_ALT = 1

;**********************************************************************************************;
; @section : CTRLC - Control C                                                                 ;
;**********************************************************************************************;

; CTRLC - TCA0 Waveform Output 5
.EQU PORTMUX_CTRLC_TCA05_DEF = 0
.EQU PORTMUX_CTRLC_TCA05_ALT = 1

; CTRLC - TCA0 Waveform Output 4
.EQU PORTMUX_CTRLC_TCA04_DEF = 0
.EQU PORTMUX_CTRLC_TCA04_ALT = 1

; CTRLC - TCA0 Waveform Output 3
.EQU PORTMUX_CTRLC_TCA03_DEF = 0
.EQU PORTMUX_CTRLC_TCA03_ALT = 1

; CTRLC - TCA0 Waveform Output 2
.EQU PORTMUX_CTRLC_TCA02_DEF = 0
.EQU PORTMUX_CTRLC_TCA02_ALT = 1

; CTRLC - TCA0 Waveform Output 1
.EQU PORTMUX_CTRLC_TCA01_DEF = 0
.EQU PORTMUX_CTRLC_TCA01_ALT = 1

; CTRLC - TCA0 Waveform Output 0
.EQU PORTMUX_CTRLC_TCA00_DEF = 0
.EQU PORTMUX_CTRLC_TCA00_ALT = 1

;**********************************************************************************************;
; @section : CTRLD - Control D                                                                 ;
;**********************************************************************************************;

; CTRLD - TCB0 Waveform Output
.EQU PORTMUX_CTRLD_TCB0_DEF = 0
.EQU PORTMUX_CTRLD_TCB0_ALT = 1
