;**************************************************************;
; @section : Register Definition                               ;
;**************************************************************;

.IFNDEF REGISTERS
.SET    REGISTERS = 1

.DEF BUFFL = r14
.DEF BUFFH = r15

.DEF TEMPL = r16
.DEF TEMPH = r17

.DEF INT_TEMPL = r18
.DEF INT_TEMPH = r19

.DEF ARG1 = r20
.DEF ARG2 = r21
.DEF ARG3 = r22
.DEF ARG4 = r23

.ENDIF
