.INCLUDE "evsys/define/evsys-define.inc"

;**
;** @brief  Event System - Asynchronous Channel 0 Generator Selection
;**
;** @value  
;**
.EQU CONFIG_EVSYS_ASYNC_CHANNEL0_GENERATOR = EVSYS_ASYNC_CHANNEL0_GENERATOR_NONE

;**
;** @brief  Event System - Asynchronous Channel 1 Generator Selection
;**
;** @value  
;**
.EQU CONFIG_EVSYS_ASYNC_CHANNEL1_GENERATOR = EVSYS_ASYNC_CHANNEL1_GENERATOR_NONE

;**
;** @brief  Event System - 16-Bit Timer/Counter Type B 0 Input Selection
;**
;** @value  
;**
.EQU CONFIG_EVSYS_TCB0_INPUT = EVSYS_TCB0_INPUT_NONE

;**
;** @brief  Event System - Analog-to-Digital Converter 0 Input Selection
;**
;** @value  
;**
.EQU CONFIG_EVSYS_ADC0_INPUT = EVSYS_ADC0_INPUT_NONE
