.INCLUDE "portmux/portmux-def.inc"

;**
;** @brief  CCL LUT 1 Output
;**
;** @value  CCL LUT 1 Output Configuration Options
;**
.EQU CONFIG_PORTMUX_CCL_LUT1_PIN = PORTMUX_CCL_LUT1_PIN_DEFAULT

;**
;** @brief  CCL LUT 0 Output
;**
;** @value  CCL LUT 0 Output Configuration Options
;**
.EQU CONFIG_PORTMUX_CCL_LUT0_PIN = PORTMUX_CCL_LUT0_PIN_DEFAULT

;**
;** @brief  Event Output 2
;**
;** @value  Event Output 2 Configuration Options
;**
.EQU CONFIG_PORTMUX_EVENT_OUTPUT2 = PORTMUX_EVENT_OUTPUT2_DISABLED

;**
;** @brief  Event Output 1
;**
;** @value  Event Output 1 Configuration Options
;**
.EQU CONFIG_PORTMUX_EVENT_OUTPUT1 = PORTMUX_EVENT_OUTPUT1_DISABLED

;**
;** @brief  Event Output 0
;**
;** @value  Event Output 0 Configuration Options
;**
.EQU CONFIG_PORTMUX_EVENT_OUTPUT0 = PORTMUX_EVENT_OUTPUT0_DISABLED

;**
;** @brief  TWI0 Communication
;**
;** @value  TWI0 Communication Configuration Options
;**
.EQU CONFIG_PORTMUX_TWI0_PIN = PORTMUX_TWI0_PIN_DEFAULT

;**
;** @brief  SPI0 Communication
;**
;** @value  SPI0 Communication Configuration Options
;**
.EQU CONFIG_PORTMUX_SPI0_PIN = PORTMUX_SPI0_PIN_DEFAULT

;**
;** @brief  USART0 Communication
;**
;** @value  USART0 Communication Configuration Options
;**
.EQU CONFIG_PORTMUX_USART0_PIN = PORTMUX_USART0_PIN_DEFAULT

;**
;** @brief  TCA0 Waveform Output 5
;**
;** @value  TCA0 Waveform Output 5 Configuration Options
;**
.EQU CONFIG_PORTMUX_TCA0_WAVEFORM_OUTPUT5_PIN = PORTMUX_TCA0_WAVEFORM_OUTPUT5_PIN_DEFAULT

;**
;** @brief  TCA0 Waveform Output 4
;**
;** @value  TCA0 Waveform Output 4 Configuration Options
;**
.EQU CONFIG_PORTMUX_TCA0_WAVEFORM_OUTPUT4_PIN = PORTMUX_TCA0_WAVEFORM_OUTPUT4_PIN_DEFAULT

;**
;** @brief  TCA0 Waveform Output 3
;**
;** @value  TCA0 Waveform Output 3 Configuration Options
;**
.EQU CONFIG_PORTMUX_TCA0_WAVEFORM_OUTPUT3_PIN = PORTMUX_TCA0_WAVEFORM_OUTPUT3_PIN_DEFAULT

;**
;** @brief  TCA0 Waveform Output 2
;**
;** @value  TCA0 Waveform Output 2 Configuration Options
;**
.EQU CONFIG_PORTMUX_TCA0_WAVEFORM_OUTPUT2_PIN = PORTMUX_TCA0_WAVEFORM_OUTPUT2_PIN_DEFAULT

;**
;** @brief  TCA0 Waveform Output 1
;**
;** @value  TCA0 Waveform Output 1 Configuration Options
;**
.EQU CONFIG_PORTMUX_TCA0_WAVEFORM_OUTPUT1_PIN = PORTMUX_TCA0_WAVEFORM_OUTPUT1_PIN_DEFAULT

;**
;** @brief  TCA0 Waveform Output 0
;**
;** @value  TCA0 Waveform Output 0 Configuration Options
;**
.EQU CONFIG_PORTMUX_TCA0_WAVEFORM_OUTPUT0_PIN = PORTMUX_TCA0_WAVEFORM_OUTPUT0_PIN_DEFAULT

;**
;** @brief  TCB0 Waveform Output
;**
;** @value  TCB0 Waveform Output Configuration Options
;**
.EQU CONFIG_PORTMUX_TCB0_WAVEFORM_OUTPUT_PIN = PORTMUX_TCB0_WAVEFORM_OUTPUT_PIN_DEFAULT
